### ISSUE TITLE
NewPanicHandler is quite broken

### ISSUE THREAD

**Issue by jim-minter** [Azure/go-shuttle#109]
v2/NewPanicHandler has several issues:

https://github.com/Azure/go-shuttle/blob/39a27229d1bed713ed674d06216d83fe46a59e63/v2/processor.go#L137-L146

1. The `defer` statement is in the wrong place - it needs to be inside the `return func` to have any effect.  At the moment it's a no-op.
2. No unit test coverage.
3. A panic handler which recovers a panic and then panics again doesn't seem very useful to me.

I'd send a fix for (1/2), but I'm not at all sure what this code is intended to do, so am leaving this issue for the maintainers to decide.

**Comment by jim-minter** [comment]
@serbrech

**Comment by serbrech** [comment]
I'm aware. It's not doing anything.
In any of our usage, we use our internal panic ha sleep middleware, so I have not prioritized it.
