### ISSUE TITLE
Provide a way to disable entities auto-creation

### ISSUE THREAD

**Issue by serbrech** [Azure/go-shuttle#26]
Go shuttle tries to simplify the setup of the client application by providing a minimal, discoverable, and extensible API to start publishing or receiving messages.

To do so, it auto-creates the topics and subscriptions when creating a Publisher/Listener.

I like this to be the default behavior, but it should be possible to disable entities operations if needed.

##This would for example allow to reduce the required rights of the user that runs the receiver or publisher.

**Comment by coip** [comment]
thoughts on

default behaviour: non-mutative => no attempt @ mgmt ops, only pub/sub.
& adapting ensureTopic as a `ManagementOption`?

that way, services can consume shuttle as a servicebus wrapper w ~PoLP baked in on default path w/o added explcit config? 

Im coming from a service-ops perspective on this, but do see merit to `default ensure` when considering your approach from a dev experience mindset...

**Comment by serbrech** [comment]
resolved with v2, which never auto-creates any entity. leaves it to the user to do that with the sdk client.
