### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by serbrech** [Azure/go-shuttle#27]
Build
Lint
Run unit tests
Code metrics
Run integration tests
ReleaseNotes generation on labels

**Comment by coip** [comment]
GH actions an acceptable ~execution env for yall?

**Comment by coip** [comment]
from my current perspective, seems the only op here I couldnt handle would be adding a `secret` to the repo for injecting the `CONNSTR` that the int suite consumes/depends on, and the GH labels mgmt (unfamiliar).

wiring that into the workflow.yml would be easy though.

I may be able to help a bit on this front if GH is acceptable, all but labels functionality would be easy enough as I have boiler already.

**Comment by serbrech** [comment]
I'll have to get back to you on this.
we'll be using an internal Azure subscription. thanks for looking into it!

**Comment by coip** [comment]
“Diversification”, right? 😄
https://twitter.com/architektn/status/1535082153939464192?s=21&t=fMjF3sJCKNLnXZaEO-Yhmw

**Comment by serbrech** [comment]
stale
