### ISSUE TITLE
Support for Queues (alongside topics)

### ISSUE THREAD

**Issue by coip** [Azure/go-shuttle#39]
unsure if topics would be plug-n-play for use-cases in mind, but I currently depend on the queue servicebus primitive and would like to move to a pkg like this instead of the vanilla `azure-service-bus-go` lib

topics might complicate it, might not. Im uninitiated beyond the perspective of topics being a means of fanning out to N subscribers (where services I have in mind are currently point-to-point, only consuming queues in the azure-service-bus-go lib)

appreciate any thoughts, TIA

**Comment by serbrech** [comment]
The way I like to look at it is that Topics-subscribers is for eventing, while queues are for command style of messages.
The difference is in who owns the message contract.

With eventing, the emitter owns the contract, so the listeners take a dependency on the emitter.

With queues, it's the consumer who owns the contract, and so the sender takes a dependency on the receiver.

Queues allow to plug asynchronous processing behind an api. Events allow to decouple services.

That's the 90% of the use case I have seen.
Although, it's not a rule, you can use them however you like.

We plan to add queues to go-shuttle very soon to cover our use-cases.

**Comment by coip** [comment]
good frame for considering the paradigms, appreciate your thoughts and the direction this projects taking 🙌 🥳
