### ISSUE TITLE
Parallel message handling does not work

### ISSUE THREAD

**Issue by charliedmcb** [Azure/go-shuttle#8]
### Which version of the SDK was used?
github.com/Azure/go-shuttle v0.5.5
https://github.com/Azure/go-shuttle/tree/8da14c485b239d55fa6b75dd41704e7d3bd0e55f

### Which platform are you using? (ex: Windows, Linux, Debian)
Linux

### What problem was encountered?
How things are currently set up in go-shuttle I am only able to process one message from the service bus at a time, and don't get to move onto the next message until the first is completed. I have been unable to find any exposed feature that would allow me to handle concurrent messages.

From digging through the code base I found that there are a few locations in the dependency azure-service-bus-go that I believe are resulting in this behavior, with modification to go-shuttle I expect that either exposing a setting, a new AsyncListener or something similar could allow for concurrent handling of messages:
1. where handle message is called we get a blocking call until the handler completes the message:
https://github.com/Azure/azure-service-bus-go/blob/705d23958eb9c000582c03ba30413dc7e35eb25d/receiver.go#L235
2. PeakAndLock mode is the default, and not exposed to the user. From my understanding this means that the message will not be removed from the queue until it is completed meaning that we would not even be able to create additional Listeners to receive more messages, as we would still be blocked until the locked message was completed and removed (I expect this should not be changed, and most likely does not want to be exposed either):
https://github.com/Azure/azure-service-bus-go/blob/705d23958eb9c000582c03ba30413dc7e35eb25d/receiver.go#L108
3. The prefetchCount/linkCredit is set to 1 as default, and there is no setting exposed from go-shuttle to set it:
https://github.com/Azure/azure-service-bus-go/blob/705d23958eb9c000582c03ba30413dc7e35eb25d/receiver.go#L109

An additional note: as RetryLater simply pauses the process in memory, but doesn't remove the message from the queue we are unable to progress onto the next message until we actually complete it. I expect this in intended behavior, but wanted to make note.

### How can we reproduce the problem in the simplest way?
Create a Azure Service Bus namespace, and a topic
Setup a go-shuttle Listener for the topic
Enqueue multiple messages
Only one message will be handled at a time with no parallelism

### Have you found a mitigation/solution?
While working with a few others we have not found a solution yet, but have run some informative tests and have some ideas:
1. I modified code location 1. to ```go r.handleMessage(ctx, msg, handler)```, and code location 2. to ```mode:       ReceiveAndDeleteMode,```. When running a repro test with this I was successfully able to handle the messages in parallel. I expect modifying the first code location is probably not ok as I believe it possibly changes the current behavior, but might be an alright change. I believe it would need more knowledgeable voices in the mix and isn't even for this repo. However, I highly expect that modifying ```ReceiveAndDeleteMode``` is not an acceptable solution as it changes the default behavior. I believe even exposing the option to use it in go-shuttle is not an acceptable final solution as in my understanding in the event that the consuming service crashes the message would be lost.
2. Working with a few other people Xiahe found the following PR that gives an example of how to implement concurrency using the azure-service-bus-go lib: https://github.com/Azure/azure-service-bus-go/pull/117/files. Based of this PR, Paul Miller created a strawman PR in go-shuttle to emulate what the example PR showed: https://github.com/Azure/go-shuttle/pull/9. I ran a repro test using this PR and was able to confirm that it worked correctly; although, it was limited to handling the number of messages equal to Paul's concurrency value which is used to set the prefetchCount/linkCredit.

I believe the most likely solution will involve something similar to Paul's PR exposed as a new AsyncListener with an option to adjust what the concurrency value is set to, or modify the current Listener and add an exposed option to adjust what the concurrency is set to with the default staying at 1.

**Comment by serbrech** [comment]
Thanks for investigating Charlie, 

1 and 3 are indeed correct.
- We want to increase the link credit in go-amqp, which will allow more than 1 message "in flight" for the amqp connection. That will allow **concurrent receives**
- The message handler needs to be run in a go-routine. That will enable **concurrent processing**

Batching (prefetch value) is a separate concern from concurrent receives and concurrent handling. It allows to improve performance by reducing the number of round-trips, and it definitely needs to be exposed and tuned.

`PeekLock` is not related to the concurrent processing that we need and should not be changed. It protects you against concurrent processing **of the same message**, which is what you want in 90% of cases. 
One case where you need to change it would be to implement a competing consumer pattern.

RetryLater behaviour is intended, and will be just fine once we have concurrent message processing :)

About a solution, I believe concurrent processing should be the default, with sane link credit and prefetch default value.
there shouldn't be a need to expose a specific Async listener. I would rather have an async listener, but let the user set concurrency values.
there is 3 aspects to this.

1. Local listener concurrency (how many concurrent worker do you want your program to run). This depends on the resources available and on the type of processing each message does (network/cpu intensive for example)
2. Prefetch count (how many message do we fetch at once). this depends on available throughput and needs tuning.
3. link credit is probably a factor of 1 and 2.

Crawl, Walk, Run :)
